from . import workshop_config
from . import workshop_vehicle
from . import workshop_order
from . import workshop_checklist
from . import workshop_billing
from . import res_partner
from . import res_config_settings
from . import res_users
from . import workshop_demo
