from . import workshop_stage
from . import workshop_location
from . import workshop_sector
from . import workshop_service
from . import workshop_vehicle
from . import workshop_checklist_template
from . import res_config_settings
from . import res_company
from . import workshop_order
from . import workshop_billing
from . import workshop_demo
from . import res_partner
from . import res_users
from . import res_users_settings
from . import ir_http
